### ISSUE TITLE
Adding a typeless .Has() and .Get() methods for entity.

### ISSUE THREAD

**Issue by Cream256** [thygrrr/fennECS#22]
Could we expect to have methods for adding/removing components that do not require generic arguments?
Like: `entity.Has(myComponent.GetType())`?

This is the list of methods that I need on Entity class. They are similar to the GetVirtual and HasVirtual method. Maybe if we add the above method, the virtual ones won't be needed anymore.
```
1. bool Has(Type componentType);
2. object Get(Type componentType);
3. void Remove(Type componentType);
```

I can work around the 1 and 2, but number 3 is more tricky, since I don't have access to the world internal methods to do this. I would have to compile a custom branch of Fennecs, which I don't want to do right now.

**Comment by thygrrr** [comment]
Working on this right now, almost done.
