### ISSUE TITLE
Implement RW and R ref structs for Stream.For and Stream.Job

### ISSUE THREAD

**Issue by thygrrr** [thygrrr/fennECS#32]
```cs
stream.For(
    uniform: Time.Delta, 
    action: (in Entity e, float dt, ref Vector3 velocity) => 
    {
        velocity.Y -= 9.81f * dt;
    }
);
```

### Disadvantages
- Uniform gets copied each time and can't possibly be a ref (but can be a ref type)
- Entity struct needs be created and copied each time, this was improved 50% with the `in` keyword
- verbose (only explicit parameters supported, no type infernece possible, `in` keyword sadly not an option as low-level C# can't tell it apart from `ref`)
- no way to detect write modifications

# Change
> We want to replace the refs with `ref structs` `R<C>` and `RW<C` that can be read or written.

## Syntax / Semantics
- no more explicit requirements: together with .NET 9.0 `OverloadResolutionPriorityAttribute`, this means the entire signature of the Runner can be inferred from what happens inside the runner.
```cs
 stream.For(
    uniform: Time.Delta, 
    action: (e, dt, velocity) => 
    {
        velocity.Y -= 9.81f * dt;
    }
);
```
- code completion plays more nicely with this
- explicit syntax still available, and actually *shorter than* the old explicit syntax
- uniform could in theory now be a `ref`

## Read Write Detection
- reading components requires the user to type `.read` or `.write` to access the specific struct, improving code readability
- these accessors will be used to notify subscribers to write changes to components (See `fennecs.events.Added/Removed/Modified`)
- internal reflection usage results in 0 performance impact for components without listener support
- these accessors can be used to lock and unlock chunks or archetypes (for parallelization)
- the struct has an internal `ref` to the Entity, and can expose a convenient `Remove()` directly on the component.
- this enables various shortcuts, including `.consume` semantics

## Disadvantages
- Entity can't be a `ref` or `in` (requires explicit syntax), but `in` overloads could be provided.
- `.read` or `.write` is technically more boilerplate

**Comment by xentripetal** [comment]
Once R/W notifications are in place, are you considering adding Changed/Removed query matchers?
