### ISSUE TITLE
MacOS Linking Issue?

### ISSUE THREAD

**Issue by xentripetal** [thygrrr/fennECS#4]
I've never seen this before, but when testing out Fennecs on MacOS M1 it fails to link in the dll. This is true both for 0.0.7 nuget package and pulling master and compiling it as part of the same sln. 

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'fennecs, Version=0.0.7.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'fennecs, Version=0.0.7.0, Culture=neutral, PublicKeyToken=null'
```

I don't believe its a localized dotnet issue as I'm able to load in many other nuget packages without issue.

-- EDIT

Its from specifically only targeting x64

```xml
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>
```

Is this intentional? Removing it and everything seems to work fine on aarch64

**Comment by thygrrr** [comment]
Awesome, tank you for the input, I'll look into this ASAP!
I think Arm64 should also be supported, this was an oversight.

Still early days. :) This input is so valuable!
